name: snapcraft

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch: {}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  crafting:
    runs-on: ubuntu-latest
    env:
      SNAP_NAME: "openfunscripter"     
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: 'true'
          fetch-depth: 0
         
      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0
        env:
          GITHUB_TOKEN: ${{github.token}}

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2.1.1
        #with:
            #use_lxd: true
            
      - name: Build
        run: |
          sg lxd -c 'snapcraft'
      
      - name: Get snap name
        run: |
          echo "SNAP_NAME=$(ls *.snap)" >> $GITHUB_ENV
      
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: ${{env.SNAP_NAME}}
          asset_name: OFS-64x_${{github.ref}}-${{github.sha}}.snap
          asset_content_type: application/octet-stream
      
      #- uses: actions/upload-artifact@v4.3.1
      #  with:
      #    name: snap
      #    path: "*.snap"
